### ISSUE TITLE
Helper function for Button 

### ISSUE THREAD

**Issue by micgro42** [jmp00000001/dokuwiki_plugin_hidesectioneditbutton#1]
Instead of directly implementing the button in the toc, create a helper functionality so the button can be easily integrated in templates.

See for reference https://www.dokuwiki.org/plugin:tagging

**Comment by micgro42** [comment]
To test that functionality you could create a `pageheader.html` in your `dokuwiki/conf/`-directory and put the template code in there. For further information see: https://www.dokuwiki.org/template:dokuwiki

**Comment by jmp00000001** [comment]
done
